version: '3.3'

services:
  bip_backend:
    container_name: container-backend
    build: ./
    #command: ./BIP_backend
    ports:
      - "8080:8080"
    volumes:
      - ./.storage:/back/.storage
      - ./cmd:/back/cmd
      - ./configs:/back/configs
      - ./docs:/back/docs
      - ./internal:/back/internal
      - ./middleware:/back/middleware
      - ./migrations:/back/migrations
    depends_on:
      - db
      - pgadmin
      - redis
      - rediskey

  db:
    restart: always
    container_name: container-postgresdb
    image: postgres:latest
    volumes:
      - ./.storage/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bip_db
    ports:
      - "5436:5432"

  pgadmin:
    restart: always
    container_name: container-pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

  redis:
    restart: always
    container_name: container-redis
    image: redis
    volumes:
      - ./.storage/redis/data:/data
    command: redis-server --requirepass admin
    ports:
      - "6379:6379"

  rediskey:
    restart: always
    container_name: container-redis2
    image: redis
    volumes:
      - ./.storage/redis2/data:/data
    command: redis-server --requirepass admin
    ports:
      - "6381:6379"
